export interface Point {
  x: number;
  y: number;
}

export type ToolType = 'select' | 'hand' | 'pen' | 'smooth-pen' | 'highlighter' | 'eraser' | 'laser' | 'pointer' | 'text' | 'rect' | 'circle' | 'arrow';

export type BackgroundType = 'white' | 'black' | 'grid' | 'lines' | 'dots';

export interface Stroke {
  id: string;
  points: number[];
  color: string;
  tool: 'pen' | 'smooth-pen' | 'highlighter' | 'eraser' | 'laser';
  size: number;
  opacity?: number;
  createdAt?: number;
}

export interface ImageObj {
  id: string;
  type: 'image';
  src: string;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation?: number;
}

export interface TextObj {
  id: string;
  type: 'text';
  text: string;
  x: number;
  y: number;
  fontSize: number;
  color: string;
}

export interface ShapeObj {
  id: string;
  type: 'rect' | 'circle' | 'arrow';
  x: number;
  y: number;
  width?: number; 
  height?: number; 
  points?: number[]; 
  color: string;
  strokeWidth: number;
}

export interface LatexObj {
  id: string;
  type: 'latex';
  text: string;
  x: number;
  y: number;
  fontSize: number;
  color: string;
}

export interface CodeObj {
  id: string;
  type: 'code';
  text: string;
  language: string;
  x: number;
  y: number;
  width: number;
  height: number;
  fontSize: number;
}

export interface NoteObj {
  id: string;
  type: 'note';
  text: string;
  x: number;
  y: number;
  width: number;
  height: number;
  color: string; 
}

// CodeBlock with controls
export interface CodeBlockControl {
  id: string;
  type: 'slider' | 'number' | 'text' | 'checkbox';
  label: string;
  value: any;
  min?: number;
  max?: number;
  step?: number;
}

export interface CodeBlockObj {
  id: string;
  type: 'codeblock';
  code: string;
  x: number;
  y: number;
  width: number;
  height: number;
  fontSize: number;

  // Execution state
  lastExecuted?: number;
  error?: string;

  // Interactive controls (saved after execution)
  controls?: CodeBlockControl[];

  // ID of linked output object (if exists)
  outputId?: string;

  // UI state
  isFolded?: boolean;
  unfoldedHeight?: number; // Store original height when folded

  // Whether to append new viz or replace old one
  appendMode?: boolean;
}

// D3 Visualization output (separate object)
export interface D3VisualizationObj {
  id: string;
  type: 'd3viz';
  x: number;
  y: number;
  width: number;
  height: number;

  // HTML/SVG content generated by D3
  content: string;

  // Reference to source CodeBlock
  sourceCodeBlockId: string;
}

// Bookmarks / Frames
export interface FrameObj {
   id: string;
   label: string;
   x: number;
   y: number;
   scale: number; // Zoom level to restore
}
