export interface Point {
  x: number;
  y: number;
}

export type ToolType = 'select' | 'hand' | 'pen' | 'smooth-pen' | 'highlighter' | 'eraser' | 'laser' | 'pointer' | 'text' | 'rect' | 'circle' | 'arrow';

export type BackgroundType = 'white' | 'black' | 'grid' | 'lines' | 'dots';

export interface Stroke {
  id: string;
  points: number[];
  color: string;
  tool: 'pen' | 'smooth-pen' | 'highlighter' | 'eraser' | 'laser';
  size: number;
  opacity?: number;
  createdAt?: number;
  zIndex?: number;
}

export interface ImageObj {
  id: string;
  type: 'image';
  src: string;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation?: number;
  zIndex?: number;
}

export interface TextObj {
  id: string;
  type: 'text';
  text: string;
  x: number;
  y: number;
  fontSize: number;
  color: string;
  zIndex?: number;
}

export interface ShapeObj {
  id: string;
  type: 'rect' | 'circle' | 'arrow';
  x: number;
  y: number;
  width?: number;
  height?: number;
  points?: number[];
  color: string;
  strokeWidth: number;
  zIndex?: number;
}

export interface LatexObj {
  id: string;
  type: 'latex';
  text: string;
  x: number;
  y: number;
  fontSize: number;
  color: string;
  zIndex?: number;
}

export interface CodeObj {
  id: string;
  type: 'code';
  text: string;
  language: string;
  x: number;
  y: number;
  width: number;
  height: number;
  fontSize: number;
  zIndex?: number;
}

export interface NoteObj {
  id: string;
  type: 'note';
  text: string;
  x: number;
  y: number;
  width: number;
  height: number;
  color: string;
  zIndex?: number;
}

// CodeBlock with controls
export interface CodeBlockControl {
  id: string;
  type: 'slider' | 'number' | 'text' | 'checkbox' |
        'radio' | 'color' | 'select' | 'range' | 'button' | 'toggle';
  label: string;
  value: any;
  min?: number;
  max?: number;
  step?: number;
  options?: string[];        // For radio, select
  minValue?: number;         // For range (lower bound)
  maxValue?: number;         // For range (upper bound)
  clickCount?: number;       // For button
  lastClicked?: number;      // For button timestamp
}

export interface CodeBlockObj {
  id: string;
  type: 'codeblock';
  code: string;
  x: number;
  y: number;
  width: number;
  height: number;
  fontSize: number;

  // Execution state
  lastExecuted?: number;
  error?: string;

  // Interactive controls (saved after execution)
  controls?: CodeBlockControl[];

  // ID of linked output object (if exists)
  outputId?: string;

  // UI state
  isFolded?: boolean;
  unfoldedHeight?: number; // Store original height when folded

  // Whether to append new viz or replace old one
  appendMode?: boolean;

  zIndex?: number;
  executionTrigger?: number;  // Timestamp to trigger execution from visualization

  // Execution context for running with custom control values (for updating specific visualizations)
  executionContext?: {
    vizId: string;  // Target visualization to update
    controlValues: Record<string, any>;  // Control values to use for this execution
  };

  // Animation state
  animationId?: string;  // ID of associated animation
  isRecording?: boolean;  // Whether currently recording keyframes
  recordingStartTime?: number;  // Timestamp when recording started
}

// D3 Visualization output (separate object)
export interface D3VisualizationObj {
  id: string;
  type: 'd3viz';
  x: number;
  y: number;
  width: number;
  height: number;

  // HTML/SVG content generated by D3
  content: string;

  // Reference to source CodeBlock
  sourceCodeBlockId: string;

  zIndex?: number;
  showControls?: boolean;  // Whether to display attached controls

  // Snapshot of control values when this visualization was created
  // Each visualization has its own independent control values
  controlValues?: Record<string, any>;
}

// Bookmarks / Frames
export interface FrameObj {
   id: string;
   label: string;
   x: number;
   y: number;
   scale: number; // Zoom level to restore
}

// Animation System
export interface Keyframe {
  id: string;
  time: number;  // Time in seconds from animation start
  controlValues: Record<string, any>;  // Snapshot of all control values
  label?: string;  // Optional label for this keyframe
}

export interface Animation {
  id: string;
  codeBlockId: string;
  keyframes: Keyframe[];
  duration: number;  // Total duration in seconds
  fps: number;  // Frames per second for playback
  loop?: boolean;  // Whether to loop the animation
}

// Board API for code blocks to interact with whiteboard elements
export interface BoardAPI {
  // Reading elements
  getImages: () => Omit<ImageObj, 'type'>[];
  getTexts: () => Omit<TextObj, 'type'>[];
  getShapes: () => Omit<ShapeObj, 'type'>[];
  getLatex: () => Omit<LatexObj, 'type'>[];
  getStrokes: () => Stroke[];
  getVisualizations: () => Omit<D3VisualizationObj, 'type'>[];
  getAll: () => {
    images: Omit<ImageObj, 'type'>[];
    texts: Omit<TextObj, 'type'>[];
    shapes: Omit<ShapeObj, 'type'>[];
    latex: Omit<LatexObj, 'type'>[];
    strokes: Stroke[];
    visualizations: Omit<D3VisualizationObj, 'type'>[];
  };

  // Creating elements (returns element ID)
  addImage: (props: Partial<Omit<ImageObj, 'id' | 'type'>>) => string;
  addText: (props: Partial<Omit<TextObj, 'id' | 'type'>>) => string;
  addShape: (props: Partial<Omit<ShapeObj, 'id' | 'type'>>) => string;
  addLatex: (props: Partial<Omit<LatexObj, 'id' | 'type'>>) => string;

  // Updating elements
  updateElement: (id: string, updates: any) => void;

  // Deleting elements
  deleteElement: (id: string) => void;

  // Utility
  getViewport: () => { x: number; y: number; zoom: number };
  getCodeBlockPosition: () => { x: number; y: number; width: number; height: number };
}
